image: registry.gitlab.com/quantumsim/testing

stages:
- build
- test
- deploy
- finalize

build html documentation:
  stage: build
  script:
  - python3 setup.py install
  - cd doc && make html
  artifacts:
    paths:
    - doc/build/html
    expire_in: 1 hour

run tests:
  stage: test
  script:
  - python3 setup.py install
  - py.test

check for broken links in doc:
  stage: test
  script:
  - cd doc && make linkcheck
  allow_failure: true

upload documentation to docs repo:
  stage: deploy
  only:
  - master@quantumsim/quantumsim
  - qs2/master@quantumsim/quantumsim
  script:
  - mkdir -p ~/.ssh && touch ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - echo "${QUANTUMSIM_DOC_DEPLOY_KEY}" | base64 -d > ~/.ssh/id_rsa
  - cd doc/build/html
  - git init
  - git config --local user.name "quantumsim ci worker"
  - git config --local user.email "quantumsim@nomail"
  - git remote add docs_deploy_origin "${QUANTUMSIM_DOC_GIT_URL}"
  - git checkout -b ${CI_COMMIT_REF_NAME}
  - git add .
  - git commit --allow-empty -m "deploy docs for ${CI_COMMIT_TAG:-$CI_COMMIT_SHA}"
  - git push --force docs_deploy_origin ${CI_COMMIT_REF_NAME}

trigger website rebuild:
  stage: finalize
  only:
  - master@quantumsim/quantumsim
  - qs2/master@quantumsim/quantumsim
  script:
  - curl --request post --form token=${QUANTUMSIM_WEBSITE_TRIGGER_TOKEN}
    --form ref=master
    ${QUANTUMSIM_GITLAB_URL}/api/v4/projects/${QUANTUMSIM_WEBSITE_PROJECTID}/trigger/pipeline
