image: registry.gitlab.com/quantumsim/testing

stages:
- finalize

trigger website rebuild:
  stage: finalize
  script:
  - curl -X POST -F "token=${QUANTUMSIM_WEBSITE_TRIGGER_TOKEN}" -F ref=master
    https://gitlab.com/api/v4/projects/7827986/trigger/pipeline
